---
- name: Setup Web Server
  hosts: webservers
  become: yes # ขอสิทธิ์ sudo ในการทำงาน

  tasks:
    - name: Install Nginx package
      apt: # ใช้โมดูล apt (สำหรับ Ubuntu/Debian)
        name: nginx
        state: present # ต้องการให้มีการติดตั้งอยู่ (Declarative)
        update_cache: yes # เหมือนสั่ง apt update ก่อน

    - name: Copy custom index.html
      copy: # ใช้โมดูล copy
        src: index.html # ไฟล์ต้นทางที่เครื่อง Control Node
        dest: /var/www/html/index.html # ตำแหน่งปลายทางบน Managed Node
        mode: "0644" # กำหนด Permission ให้ไฟล์
